### ISSUE TITLE
Error when I click on a dropdownlist with angular-keyboard !

### ISSUE THREAD

**Issue by jcstritt** [gampleman/angular-keyboard#2]
Hello. I use Angular-keyboard with a dropdownlist from bootstrap in an AngularJS directive. Sometimes when i clik on a dropdownlist, i have this message that appear : 

```
TypeError: Cannot read property 'name' of undefined
    at http://code.gampleman.eu/angular-keyboard/grunt-scripts/angular-keyboard.js:1257:35
    at Object.forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:332:20)
    at select (http://code.gampleman.eu/angular-keyboard/grunt-scripts/angular-keyboard.js:1252:13)
    at _checker (http://code.gampleman.eu/angular-keyboard/grunt-scripts/angular-keyboard.js:1293:13)
    at getSelection (http://code.gampleman.eu/angular-keyboard/grunt-scripts/angular-keyboard.js:1294:13)
    at Object.$watchCollectionAction [as fn] (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:12410:13)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:12541:29)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:12806:24)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:14314:36
    at completeOutstandingRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js:4397:10) 
```

Here's the partial code in the dropdownlist template :
![image](https://cloud.githubusercontent.com/assets/6073801/5074716/528ecee6-6e8d-11e4-880c-8cffdeeb05a7.png)

I have found that's the problem is coming when two dropdownlists are in same view and when i click one when the other is open.  Have you any idea for this issue?

**Comment by kevinrstone** [comment]
Would be nice if this were fixed, since it looks fairly easy. It's not a show stopper, but is annoying to see the errors.

Here is a jsfiddle illustrating the problem:
[https://jsfiddle.net/tg1jr9o3/4/](https://jsfiddle.net/tg1jr9o3/4/)

It happens when you empty the initial array used in the ng-repeat for a selectable. In my case, I want to use the selectable in a dynamic modal to choose search results. The results model is cleared when the user either selects a choice or cancels the modal.
